---
- hosts: localhost

  tasks:
    - name: Retrieve SSH Private Key for Login from CyberArk
      cyberark_credential:
        api_base_url: "https://pvwa.192.168.3.102.xip.io"
        validate_certs: no
        client_cert: ""
        client_key: "" 
        app_id: "Ansible"
        query: "Safe=D-LIN-ROOT-SSHKEYS;Folder=Root;Object=ANSIBLE-RHEL01-KEY"
      register: cyberark_key_response
      delegate_to: localhost
      no_log: yes

    - name: Retrieve REST API Service Account for Onboarding to CyberArk
      cyberark_credential:
        api_base_url: "https://pvwa.192.168.3.102.xip.io"
        validate_certs: no
        client_cert: ""
        client_key: "" 
        app_id: "Ansible"
        query: "Safe=D-CYBR-RESTAPI-ACCTS;Folder=Root;Object=ANSIBLE-RESTAPI-USER"
      register: cyberark_user_response
      delegate_to: localhost
      no_log: yes

    - name: Set SSH Private Key to Fact Named cyberark_secret_key
      set_fact:
        cyberark_secret_key: "{{ cyberark_key_response.result.Content }}"
      no_log: yes

    - name: Set REST API Username to Fact Named cyberark_secret_username
      set_fact:
        cyberark_secret_username: "{{ cyberark_user_response.result.UserName }}"
      no_log: yes
    
    - name: Set REST API User Password to Fact Named cyberark_secret_userpass
      set_fact:
        cyberark_secret_userpass: "{{ cyberark_user_response.result.Content }}"
      no_log: yes

- hosts: all
  connection: local 
  gather_facts: no
  vars:
    ansible_ssh_pass: "{{ hostvars['localhost']['cyberark_secret_key'] }}"
    cyberark_rest_user: "{{ hostvars['localhost']['cyberark_secret_username'] }}"
    cyberark_rest_pass: "{{ hostvars['localhost']['cyberark_secret_userpass'] }}"
    mysql_username: "demo"
    mysql_password: "Cyberark1"

  roles:
    - cyberark.modules

  tasks:
    - name: Install Apache
      yum:
        name: apache2
        state: present

    - name: Install PHP module for Apache
      yum:
        name: libapache2-mod-php5
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: running
        enabled: yes

    - name: Create index.php That Pulls from MariaDB Using CyberArk Secured Secret 
      copy:
        dest: "/var/www/html/index.php"
        content: |
          <?php echo "Hello World!"; ?>

    - name: Install MariaDB Server Package
      yum:
        name: mariadb-server
        state: present

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Install Python MySQL Package
      yum:
        name: python-mysqldb
        state: present

    - name: Create a New Database
      mysql_db:
        name: demo
        state: present
        collation: utf8_general_ci

    - name: Create a Database User
      mysql_user:
        name: "{{ mysql_username }}"
        password: "{{ mysql_password }}"
        priv: "*.*:ALL"
        host: localhost
        state: present

    - name: Authenticate to CyberArk Web Services
      cyberark_authentication:
        api_base_url: "https://pvwa.192.168.3.102.xip.io"
        validate_certs: no
        username: "{{ cyberark_rest_user }}"
        password: "{{ cyberark_rest_pass }}"

    - name: Set CyberArk Authn Token to Fact Named cyberark_authn_token
      set_fact:
        cyberark_authn_token: "{{ cyberark_session.token }}"
      no_log: yes

    - name: Onboard MySQL Local User to CyberArk EPV
      uri:
        url: https://pvwa.192.168.3.102.xip.io/PasswordVault/api/Accounts/
        headers:
          Content-Type: application/json
          Authorization: "{{ cyberark_authn_token }}"
        method: POST 
        status_code: 201
        body:
          name: "MYSQL-DEMO-USER"
          address: "rhel01.192.168.3.104.xip.io"
          userName: "{{ mysql_username }}"
          platformId: "MySQL"
          safeName: "D-MYSQL-LOCAL-USERS"
          secretType: "password"
          secret: "{{ mysql_password }}"
          secretManagement:
            automaticManagementEnabled: yes
        body_format: json
        validate_certs: no

    - name: Logoff from CyberArk Web Services
      cyberark_authentication:
        state: absent 
        cyberark_session: "{{ cyberark_session }}"

    - name: Copy sample data to local filesystem /tmp/
      copy:
        src: files/dump.sql
        dest: /tmp/dump.sql
    
    - name: Insert sample data into demo table in MySQL
      shell:
        cat /tmp/dump.sql | mysql -u '{''{ mysql_username }''}' -p '{''{ mysql_password }''}'

    - name: Install MySQL extension for PHP 
      yum:
        name: php5-mysql
        state: present

    - name: Restart Apache 
      service:
        name: apache2
        state: restarted

    - name: Install Database Connection PHP Script db.php
      copy:
        src: files/db.php
        dest: /var/www/html/db.php